import Lax20Proofs.TMToRam.Simulation

/-!
The whole-machine numeric interpreter.  `numericStmt` handles one statement;
this file adds instruction fetch from the encoded label and proves that the
result commutes with the transition function of a bundled finite TM2.
-/

namespace Lax20Proofs.TMToRam

open Turing

/-- Symbols generated by the statement stored at a machine label belong to
the finite alphabet selected for that bundled machine. -/
theorem FinTM2.generatedBy_main_available (tm : FinTM2) (l : tm.Λ) (z : Σ k, tm.Γ k)
    (hz : SigmaGeneratedBy (tm.m l) z) : z ∈ FinTM2.availableSymbols tm := by
  apply Set.mem_union_right
  letI := tm.σFin
  apply Set.mem_iUnion.mpr
  exact ⟨l, hz.mem_stmtSymbols⟩

/-- One step of the numeric interpreter.  Zero/`none` is the halted label;
an invalid positive label also halts, although correctness only uses valid
encodings. -/
noncomputable def FinTM2.numericStep (tm : FinTM2) :
    NumericMachineState → Option NumericMachineState := by
  letI := tm.ΛFin
  exact fun c =>
    match c.label with
    | none => none
    | some code =>
        match finDecode tm.Λ code with
        | none => none
        | some l => some ((numericStmt tm (tm.m l)
            (FinTM2.generatedBy_main_available tm l)).exec c)

/-- The numeric interpreter implements exactly one bundled TM2 transition on
every configuration satisfying the reachable-symbol invariant. -/
theorem FinTM2.numericStep_encode (tm : FinTM2) (c : tm.Cfg)
    (hc : StacksWithin (FinTM2.availableSymbols tm) c.stk) :
    FinTM2.numericStep tm (FinTM2.encodeNumericState tm c hc) =
      match h : tm.step c with
      | none => none
      | some c' => some (FinTM2.encodeNumericState tm c'
          (FinTM2.step_stacksWithin tm c c' hc h)) := by
  letI := tm.kFin
  letI := tm.ΛFin
  letI := tm.σFin
  letI : DecidableEq tm.K := tm.kDecidableEq
  letI : DecidableEq tm.Λ := Classical.decEq _
  letI : DecidableEq tm.σ := Classical.decEq _
  rcases c with ⟨l, s, S⟩
  cases l with
  | none =>
      simp [FinTM2.numericStep, FinTM2.encodeNumericState, FinTM2.step]
  | some l =>
      have hsim := numericStmt_exec_encode tm (tm.m l)
        (FinTM2.generatedBy_main_available tm l) (some l) s S hc
      simp only [FinTM2.step]
      unfold FinTM2.numericStep
      simp only [FinTM2.encodeNumericState, Option.map_some, finDecode_finCode]
      exact congrArg some (by simpa [FinTM2.encodeNumericState] using hsim)

/-- Convenient non-dependent successor form of `numericStep_encode`. -/
theorem FinTM2.numericStep_encode_some (tm : FinTM2) (c c' : tm.Cfg)
    (hc : StacksWithin (FinTM2.availableSymbols tm) c.stk)
    (hs : tm.step c = some c') :
    FinTM2.numericStep tm (FinTM2.encodeNumericState tm c hc) =
      some (FinTM2.encodeNumericState tm c'
        (FinTM2.step_stacksWithin tm c c' hc hs)) := by
  letI := tm.kFin
  letI := tm.ΛFin
  letI := tm.σFin
  letI : DecidableEq tm.K := tm.kDecidableEq
  letI : DecidableEq tm.Λ := Classical.decEq _
  letI : DecidableEq tm.σ := Classical.decEq _
  rcases c with ⟨l, s, S⟩
  cases l with
  | none => simp [FinTM2.step] at hs
  | some l =>
      change some (TM2.stepAux (tm.m l) s S) = some c' at hs
      injection hs with hc'
      subst c'
      unfold FinTM2.numericStep
      simp only [FinTM2.encodeNumericState, Option.map_some, finDecode_finCode]
      exact congrArg some (by
        simpa [FinTM2.encodeNumericState] using
          numericStmt_exec_encode tm (tm.m l)
            (FinTM2.generatedBy_main_available tm l) (some l) s S hc)

/-- Iterating an option-valued transition from `none` remains `none`. -/
theorem iterate_bind_none {α : Type} (step : α → Option α) (t : ℕ) :
    ((fun o : Option α => o.bind step)^[t]) none = none := by
  induction t with
  | zero => rfl
  | succ t ih => simpa [Function.iterate_succ_apply] using ih

/-- Whole-run correctness of the numeric interpreter.  Besides the final
encoded state, the theorem returns the invariant proof needed to continue
the simulation.  The simulated trace has exactly the same number of machine
transitions as the typed trace. -/
theorem FinTM2.numeric_iterate_encode (tm : FinTM2) (t : ℕ) (c c' : tm.Cfg)
    (hc : StacksWithin (FinTM2.availableSymbols tm) c.stk)
    (hrun : ((fun o : Option tm.Cfg => o.bind tm.step)^[t]) (some c) = some c') :
    ∃ hc' : StacksWithin (FinTM2.availableSymbols tm) c'.stk,
      ((fun o : Option NumericMachineState => o.bind (FinTM2.numericStep tm))^[t])
          (some (FinTM2.encodeNumericState tm c hc)) =
        some (FinTM2.encodeNumericState tm c' hc') := by
  induction t generalizing c c' with
  | zero =>
      simp only [Function.iterate_zero_apply] at hrun ⊢
      injection hrun with hcc
      subst c'
      exact ⟨hc, rfl⟩
  | succ t ih =>
      cases hs : tm.step c with
      | none =>
          change TM2.step tm.m c = none at hs
          have : ((fun o : Option tm.Cfg => o.bind tm.step)^[t]) none = some c' := by
            rw [Function.iterate_succ_apply] at hrun
            change ((fun o : Option tm.Cfg => o.bind tm.step)^[t]) (tm.step c) =
              some c' at hrun
            simpa [hs] using hrun
          rw [iterate_bind_none] at this
          contradiction
      | some d =>
          change TM2.step tm.m c = some d at hs
          have hd : StacksWithin (FinTM2.availableSymbols tm) d.stk :=
            FinTM2.step_stacksWithin tm c d hc hs
          have htail :
              ((fun o : Option tm.Cfg => o.bind tm.step)^[t]) (some d) = some c' := by
            rw [Function.iterate_succ_apply] at hrun
            change ((fun o : Option tm.Cfg => o.bind tm.step)^[t]) (tm.step c) =
              some c' at hrun
            simpa [hs] using hrun
          obtain ⟨hc', hnum⟩ := ih d c' hd htail
          refine ⟨hc', ?_⟩
          rw [Function.iterate_succ_apply]
          simp only [Option.bind_some]
          have hstep := FinTM2.numericStep_encode_some tm c d hc hs
          rw [hstep]
          simpa only using hnum

/-- A bounded typed run yields a numeric run with the same witnessed step
count (and hence the same upper bound). -/
theorem FinTM2.numeric_evalsToInTime_encode (tm : FinTM2) (m : ℕ) (c c' : tm.Cfg)
    (hc : StacksWithin (FinTM2.availableSymbols tm) c.stk)
    (hrun : StateTransition.EvalsToInTime tm.step c (some c') m) :
    ∃ t ≤ m, ∃ hc' : StacksWithin (FinTM2.availableSymbols tm) c'.stk,
      ((fun o : Option NumericMachineState => o.bind (FinTM2.numericStep tm))^[t])
          (some (FinTM2.encodeNumericState tm c hc)) =
        some (FinTM2.encodeNumericState tm c' hc') := by
  obtain ⟨hc', hnum⟩ := FinTM2.numeric_iterate_encode tm hrun.steps c c' hc
    (by simpa only using hrun.evals_in_steps)
  exact ⟨hrun.steps, hrun.steps_le_m, hc', hnum⟩

/-- Specialization of whole-run correctness to mathlib's TM2 input/output
interface. -/
theorem FinTM2.numeric_outputsInTime (tm : FinTM2)
    (input : List (tm.Γ tm.k₀)) (output : List (tm.Γ tm.k₁)) (m : ℕ)
    (hrun : TM2OutputsInTime tm input (some output) m) :
    ∃ t ≤ m,
      ∃ hhalt : StacksWithin (FinTM2.availableSymbols tm) (haltList tm output).stk,
        ((fun o : Option NumericMachineState =>
            o.bind (FinTM2.numericStep tm))^[t])
          (some (FinTM2.encodeNumericState tm (initList tm input)
            (FinTM2.initList_stacksWithin tm input))) =
          some (FinTM2.encodeNumericState tm (haltList tm output) hhalt) := by
  exact FinTM2.numeric_evalsToInTime_encode tm m (initList tm input)
    (haltList tm output) (FinTM2.initList_stacksWithin tm input) hrun

end Lax20Proofs.TMToRam
