import Lax51Proofs.TMToRam.Program

/-!
Symbols on an internal `FinTM2` stack need not belong to a globally finite
alphabet: mathlib asks only that the input alphabet be finite.  This module
isolates the smaller set which matters to an execution.  Apart from input
symbols, every stack symbol was produced at a syntactic `push` site, applied
to one of the machine's finitely many internal states.
-/

namespace Lax51Proofs.TMToRam

open Turing

variable {K : Type} {Γ : K → Type} {Λ σ : Type}

/-- A non-dependent version of `GeneratedBy`, collecting the stack index
and its symbol into one sigma type. This is the convenient carrier for the
finiteness argument. -/
inductive SigmaGeneratedBy : TM2.Stmt Γ Λ σ → (Σ k, Γ k) → Prop
  | push_here {k : K} {f : σ → Γ k} {q : TM2.Stmt Γ Λ σ} (s : σ) :
      SigmaGeneratedBy (.push k f q) ⟨k, f s⟩
  | push_next {k : K} {f : σ → Γ k} {q : TM2.Stmt Γ Λ σ} {z : Σ k, Γ k} :
      SigmaGeneratedBy q z → SigmaGeneratedBy (.push k f q) z
  | peek_next {k : K} {f : σ → Option (Γ k) → σ}
      {q : TM2.Stmt Γ Λ σ} {z : Σ k, Γ k} :
      SigmaGeneratedBy q z → SigmaGeneratedBy (.peek k f q) z
  | pop_next {k : K} {f : σ → Option (Γ k) → σ}
      {q : TM2.Stmt Γ Λ σ} {z : Σ k, Γ k} :
      SigmaGeneratedBy q z → SigmaGeneratedBy (.pop k f q) z
  | load_next {f : σ → σ} {q : TM2.Stmt Γ Λ σ} {z : Σ k, Γ k} :
      SigmaGeneratedBy q z → SigmaGeneratedBy (.load f q) z
  | branch_left {f : σ → Bool} {q₁ q₂ : TM2.Stmt Γ Λ σ} {z : Σ k, Γ k} :
      SigmaGeneratedBy q₁ z → SigmaGeneratedBy (.branch f q₁ q₂) z
  | branch_right {f : σ → Bool} {q₁ q₂ : TM2.Stmt Γ Λ σ} {z : Σ k, Γ k} :
      SigmaGeneratedBy q₂ z → SigmaGeneratedBy (.branch f q₁ q₂) z

/-- A structural finite over-approximation of the symbols a statement can
push, assuming the internal state type is finite. -/
def stmtSymbols [Fintype σ] : TM2.Stmt Γ Λ σ → Set (Σ k, Γ k)
  | .push k f q => Set.range (fun s : σ => ⟨k, f s⟩) ∪ stmtSymbols q
  | .peek _ _ q => stmtSymbols q
  | .pop _ _ q => stmtSymbols q
  | .load _ q => stmtSymbols q
  | .branch _ q₁ q₂ => stmtSymbols q₁ ∪ stmtSymbols q₂
  | .goto _ => ∅
  | .halt => ∅

/-- The structural symbol over-approximation is finite. -/
theorem stmtSymbols_finite [Fintype σ] (q : TM2.Stmt Γ Λ σ) :
    (stmtSymbols q).Finite := by
  induction q with
  | push k f q ih =>
      exact (Set.finite_range (fun s : σ => ⟨k, f s⟩)).union ih
  | peek k f q ih | pop k f q ih | load f q ih => exact ih
  | branch f q₁ q₂ ih₁ ih₂ => exact ih₁.union ih₂
  | goto f | halt => exact Set.finite_empty

/-- Every symbol described by the inductive generated-symbol relation lies
in the structural finite set. -/
theorem SigmaGeneratedBy.mem_stmtSymbols [Fintype σ]
    {q : TM2.Stmt Γ Λ σ} {z : Σ k, Γ k} (h : SigmaGeneratedBy q z) :
    z ∈ stmtSymbols q := by
  induction h with
  | push_here s => exact Set.mem_union_left _ ⟨s, rfl⟩
  | push_next h ih => exact Set.mem_union_right _ ih
  | peek_next h ih | pop_next h ih | load_next h ih => exact ih
  | branch_left h ih => exact Set.mem_union_left _ ih
  | branch_right h ih => exact Set.mem_union_right _ ih

/-- `GeneratedBy q k a` means that the TM2 statement tree `q` contains a
push to stack `k` which can produce `a` at some internal state. -/
inductive GeneratedBy : TM2.Stmt Γ Λ σ → (k : K) → Γ k → Prop
  | push_here {k : K} {f : σ → Γ k} {q : TM2.Stmt Γ Λ σ} (s : σ) :
      GeneratedBy (.push k f q) k (f s)
  | push_next {j k : K} {f : σ → Γ j} {q : TM2.Stmt Γ Λ σ} {a : Γ k} :
      GeneratedBy q k a → GeneratedBy (.push j f q) k a
  | peek_next {j k : K} {f : σ → Option (Γ j) → σ}
      {q : TM2.Stmt Γ Λ σ} {a : Γ k} :
      GeneratedBy q k a → GeneratedBy (.peek j f q) k a
  | pop_next {j k : K} {f : σ → Option (Γ j) → σ}
      {q : TM2.Stmt Γ Λ σ} {a : Γ k} :
      GeneratedBy q k a → GeneratedBy (.pop j f q) k a
  | load_next {k : K} {f : σ → σ} {q : TM2.Stmt Γ Λ σ} {a : Γ k} :
      GeneratedBy q k a → GeneratedBy (.load f q) k a
  | branch_left {k : K} {f : σ → Bool} {q₁ q₂ : TM2.Stmt Γ Λ σ} {a : Γ k} :
      GeneratedBy q₁ k a → GeneratedBy (.branch f q₁ q₂) k a
  | branch_right {k : K} {f : σ → Bool} {q₁ q₂ : TM2.Stmt Γ Λ σ} {a : Γ k} :
      GeneratedBy q₂ k a → GeneratedBy (.branch f q₁ q₂) k a

/-- The dependent generated-symbol relation embeds into its sigma version. -/
theorem GeneratedBy.toSigma
    {q : TM2.Stmt Γ Λ σ} {k : K} {a : Γ k} (h : GeneratedBy q k a) :
    SigmaGeneratedBy q ⟨k, a⟩ := by
  induction h with
  | push_here s => exact .push_here s
  | push_next h ih => exact .push_next ih
  | peek_next h ih => exact .peek_next ih
  | pop_next h ih => exact .pop_next ih
  | load_next h ih => exact .load_next ih
  | branch_left h ih => exact .branch_left ih
  | branch_right h ih => exact .branch_right ih

/-- A symbol is generated by a bundled finite machine if it occurs at a
push site in the statement tree of some label. -/
def FinTM2.Generated (tm : FinTM2) (k : tm.K) (a : tm.Γ k) : Prop :=
  ∃ l : tm.Λ, GeneratedBy (tm.m l) k a

/-- All symbols occurring at push sites of a bundled finite machine. -/
def FinTM2.generatedSymbols (tm : FinTM2) : Set (Σ k, tm.Γ k) :=
  letI := tm.σFin
  ⋃ l : tm.Λ, stmtSymbols (tm.m l)

/-- The generated-symbol set of a bundled finite machine is finite. -/
theorem FinTM2.generatedSymbols_finite (tm : FinTM2) : (generatedSymbols tm).Finite := by
  letI := tm.σFin
  letI := tm.ΛFin
  exact Set.finite_iUnion (fun l => stmtSymbols_finite (tm.m l))

/-- The input symbols, tagged with the designated input stack. -/
def FinTM2.inputSymbols (tm : FinTM2) : Set (Σ k, tm.Γ k) :=
  Set.range (fun a : tm.Γ tm.k₀ => ⟨tm.k₀, a⟩)

/-- Every symbol which can occur in a run: an original input symbol or a
symbol generated at a push site. -/
def FinTM2.availableSymbols (tm : FinTM2) : Set (Σ k, tm.Γ k) :=
  inputSymbols tm ∪ generatedSymbols tm

/-- A bundled finite machine has only finitely many available symbols even
when its ambient internal stack alphabets are infinite. -/
theorem FinTM2.availableSymbols_finite (tm : FinTM2) : (availableSymbols tm).Finite := by
  letI := tm.Γk₀Fin
  exact (Set.finite_range (fun a : tm.Γ tm.k₀ => ⟨tm.k₀, a⟩)).union
    (generatedSymbols_finite tm)

/-- The finite type of tagged symbols available to `tm`. -/
def FinTM2.AvailableSymbol (tm : FinTM2) : Type :=
  {z : Σ k, tm.Γ k // z ∈ availableSymbols tm}

noncomputable instance FinTM2.AvailableSymbol.instFintype (tm : FinTM2) :
    Fintype (AvailableSymbol tm) :=
  (availableSymbols_finite tm).fintype

noncomputable instance FinTM2.AvailableSymbol.instDecidableEq (tm : FinTM2) :
    DecidableEq (AvailableSymbol tm) := Classical.decEq _

/-- The numeric code of an available tagged stack symbol. -/
noncomputable def FinTM2.symbolCode (tm : FinTM2) (z : AvailableSymbol tm) : ℕ :=
  (Fintype.equivFin (AvailableSymbol tm) z).val

theorem FinTM2.symbolCode_lt (tm : FinTM2) (z : AvailableSymbol tm) :
    symbolCode tm z < Fintype.card (AvailableSymbol tm) :=
  (Fintype.equivFin (AvailableSymbol tm) z).isLt

theorem FinTM2.symbolCode_injective (tm : FinTM2) :
    Function.Injective (symbolCode tm) := by
  intro a b h
  exact (Fintype.equivFin (AvailableSymbol tm)).injective (Fin.ext h)

/-- Available symbols belonging to one particular stack. -/
def FinTM2.AvailableAt (tm : FinTM2) (k : tm.K) : Type :=
  {a : tm.Γ k // (⟨k, a⟩ : Σ k, tm.Γ k) ∈ availableSymbols tm}

/-- Inclusion of a stack-specific available symbol into the tagged global
available alphabet. -/
def FinTM2.AvailableAt.include (tm : FinTM2) (k : tm.K) :
    AvailableAt tm k → AvailableSymbol tm :=
  fun a => ⟨⟨k, a.1⟩, a.2⟩

theorem FinTM2.AvailableAt.include_injective (tm : FinTM2) (k : tm.K) :
    Function.Injective (AvailableAt.include tm k) := by
  rintro ⟨a, ha⟩ ⟨b, hb⟩ h
  apply Subtype.ext
  have hz := congrArg Subtype.val h
  exact eq_of_heq (Sigma.mk.inj hz).2

noncomputable instance FinTM2.AvailableAt.instFintype (tm : FinTM2) (k : tm.K) :
    Fintype (AvailableAt tm k) := by
  letI : Finite (AvailableAt tm k) :=
    Finite.of_injective (FinTM2.AvailableAt.include tm k)
      (FinTM2.AvailableAt.include_injective tm k)
  exact Fintype.ofFinite _

noncomputable instance FinTM2.AvailableAt.instDecidableEq (tm : FinTM2) (k : tm.K) :
    DecidableEq (AvailableAt tm k) := Classical.decEq _

/-- Every symbol currently stored in the family of stacks belongs to `A`. -/
def StacksWithin (A : Set (Σ k, Γ k)) (S : ∀ k, List (Γ k)) : Prop :=
  ∀ (k : K) (a : Γ k), a ∈ S k → (⟨k, a⟩ : Σ k, Γ k) ∈ A

/-- An atomic TM2 statement preserves a stack alphabet containing its
incoming stacks and every symbol generated by that statement. -/
theorem stepAux_stacksWithin [DecidableEq K]
    (A : Set (Σ k, Γ k)) (q : TM2.Stmt Γ Λ σ) (s : σ) (S : ∀ k, List (Γ k))
    (hS : StacksWithin A S)
    (hgen : ∀ z, SigmaGeneratedBy q z → z ∈ A) :
    StacksWithin A (TM2.stepAux q s S).stk := by
  induction q generalizing s S with
  | push j f q ih =>
      apply ih s (Function.update S j (f s :: S j))
      · intro k a ha
        by_cases hkj : k = j
        · subst k
          rw [Function.update_self] at ha
          simp only [List.mem_cons] at ha
          rcases ha with rfl | ha
          · exact hgen _ (.push_here s)
          · exact hS j a ha
        · rw [Function.update_of_ne hkj] at ha
          exact hS k a ha
      · intro z hz
        exact hgen z (.push_next hz)
  | peek j f q ih =>
      exact ih (f s (S j).head?) S hS (fun z hz => hgen z (.peek_next hz))
  | pop j f q ih =>
      apply ih (f s (S j).head?) (Function.update S j (S j).tail)
      · intro k a ha
        by_cases hkj : k = j
        · subst k
          rw [Function.update_self] at ha
          exact hS j a (List.mem_of_mem_tail ha)
        · rw [Function.update_of_ne hkj] at ha
          exact hS k a ha
      · intro z hz
        exact hgen z (.pop_next hz)
  | load f q ih => exact ih (f s) S hS (fun z hz => hgen z (.load_next hz))
  | branch f q₁ q₂ ih₁ ih₂ =>
      by_cases hf : f s = true
      · simpa [TM2.stepAux, hf] using
          ih₁ s S hS (fun z hz => hgen z (.branch_left hz))
      · have hf' : f s = false := Bool.eq_false_of_not_eq_true hf
        simpa [TM2.stepAux, hf'] using
          ih₂ s S hS (fun z hz => hgen z (.branch_right hz))
  | goto f => exact hS
  | halt => exact hS

/-- One bundled-machine step preserves the finite available alphabet. -/
theorem FinTM2.step_stacksWithin (tm : FinTM2) (c c' : tm.Cfg)
    (hc : StacksWithin (availableSymbols tm) c.stk)
    (hstep : tm.step c = some c') :
    StacksWithin (availableSymbols tm) c'.stk := by
  cases c with
  | mk l s S =>
      cases l with
      | none => simp [FinTM2.step] at hstep
      | some l =>
          change some (TM2.stepAux (tm.m l) s S) = some c' at hstep
          injection hstep with hcfg
          subst c'
          apply stepAux_stacksWithin _ _ _ _ hc
          intro z hz
          apply Set.mem_union_right
          letI := tm.σFin
          apply Set.mem_iUnion.mpr
          exact ⟨l, hz.mem_stmtSymbols⟩

/-- The initial configuration contains only input symbols and therefore
satisfies the available-alphabet invariant. -/
theorem FinTM2.initList_stacksWithin (tm : FinTM2) (input : List (tm.Γ tm.k₀)) :
    StacksWithin (availableSymbols tm) (initList tm input).stk := by
  intro k a ha
  by_cases hk : k = tm.k₀
  · subst k
    apply Set.mem_union_left
    exact ⟨a, rfl⟩
  · have hempty : (initList tm input).stk k = [] := by
      simp [initList, hk]
    rw [hempty] at ha
    exact False.elim (by simpa using ha)

end Lax51Proofs.TMToRam
